name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pytest pytest-cov
        
    - name: Format code with Black
      run: |
        black .
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git commit -am "style: Formatação automática do código" || echo "No changes to commit"
        
    - name: Run tests
      run: |
        pytest --cov=./src tests/ || echo "No tests found"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run security checks
      run: |
        pip install bandit safety
        bandit -r ./src || echo "Security issues found"
        safety check || echo "Dependencies with known issues found"
